site:
  title: Grey Beagle Linux
  start_page: Grey Beagle Linux::index.adoc
  robots: allow
  url: https://greybeaglelinux.github.io/documentation

content:
  sources:
  - url: .
    branches: HEAD

ui:
  bundle:
    url: https://github.com/GreyBeagleLinux/antora-ui/releases/download/1.0.2/ui-bundle.zip
    snapshot: true
  supplemental_files:
  - path: ui.yml
    contents: |
      static_files:
      - .nojekyll
  - path: .nojekyll

antora:
  extensions:
  - '@antora/lunr-extension'
